---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.fullname" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ template "application.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: LoadBalancer
  ports:
  - name: web-port
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  - name: management-port
    port: {{ .Values.management.port }}
    targetPort: {{ .Values.management.port }}
  selector:
    app: {{ template "application.fullname" . }}
...